# Generated by Django 2.2.12 on 2020-05-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempreture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='memo',
        ),
    ]
